name: remote ssh command
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.DOCKER_SSH_USER }}
        key: ${{ secrets.DOCKER_SSH_KEY }}
        port: 22
        script: whoami
