name: deploy-quicknotes
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Deploying to remote cloud server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            su - docker
            cd /app
            rm -f .env
            echo "POSTGRES_PASSWORD=${{secrets.DB_PASSWORD}}" >> .env
            echo "POSTGRES_USER=${{secrets.DB_USER}}" >> .env
            echo "DUCK_DNS_TOKEN=${{secrets.DUCK_DNS_TOKEN}}" >> .env
            echo "QNS_DB_CONN_URL=postgres://${{secrets.DB_USER}}:${{secrets.DB_PASSWORD}}@db:5432/${{secrets.DB_USER}}?sslmode=disable" >> .env
            echo "QNS_MAIL_FROM=${{secrets.QNS_MAIL_FROM}}" >> .env
            echo "QNS_MAIL_HOST=${{secrets.QNS_MAIL_HOST}}" >> .env
            echo "QNS_MAIL_PORT=${{secrets.QNS_MAIL_PORT}}" >> .env
            echo "QNS_MAIL_USERNAME=${{secrets.QNS_MAIL_USERNAME}}" >> .env
            echo "QNS_MAIL_PASSWORD=${{secrets.QNS_MAIL_PASSWORD}}" >> .env
            echo "QNS_CSRF_KEY=${{secrets.QNS_CSRF_KEY}}" >> .env     
